# Generated by Django 4.0.6 on 2023-03-01 21:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nathaniel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['complete']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='userID',
        ),
        migrations.AddField(
            model_name='employee',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='written',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 21, 13, 9, 951610, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='sessions',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nathaniel.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='managerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Nathaniel.manager'),
        ),
    ]
