# Generated by Django 4.0.6 on 2023-03-01 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0002_manager_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='written',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 21, 33, 22, 994689, tzinfo=utc)),
        ),
    ]
