"""this file shows every table and every change 
to the database in this project. These changes are
known as migrations"""


# Generated by Django 4.0.6 on 2023-03-02 21:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Nathaniel', '0004_alter_employee_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='written',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 2, 21, 50, 31, 587312, tzinfo=utc)),
        ),
    ]
